name: GAUSSIAN_MIXTURE_10e3_CNF_baseBenchmarkFMPE

dim_flow: 2
dim_conditioning: 2
batch_size: 512

hidden_dim: 128
num_blocks: 10

_file: configs/benchmarks/benchmark_cnf_baseBenchmarkFMPE.yaml

data:
  target: data.benchmarks.GaussianMixture
  _file: configs/datasets/benchmarks/10e3_dataset.yaml


