optimizer:
  target: sbisim.optimization.adam.AdamOptax

scheduler:
  target: sbisim.optimization.schedules.ReduceLROnPlateau
  params:
    learning_rate: ${learning_rate}
    factor: 0.2
    patience: ${patience}
    min_lr: 1e-7

ema:
    target: sbisim.optimization.EMA
    params:
        decay: 0.9999