optimizer:
  target: sbisim.optimization.adam.AdamOptax

scheduler:
  target: sbisim.optimization.schedules.ReduceLROnPlateau
  params:
    learning_rate: ${learning_rate}
    factor: 0.2
    patience: 1
