strategy:
  target: strategy.NeuralPosteriorEstimation
  params:
    model:
      target: flows.models.fmpe.BenchmarkFMPE
      params:
        dim_flow: ${dim_flow}
        dim_conditioning: ${dim_conditioning}
        import_samples: 8
        mode: exact
        stepsize_controller_name: constant
        solver_name: tsit5
        hidden_dim: ${hidden_dim}
        num_blocks: ${num_blocks}
        out_dim: ${dim_flow}

training:
  num_epochs: 100
  num_steps_per_epoch: 1000
  batch_size: ${batch_size}

test:
  active: True
  tests:
    c2st:
      target: callbacks.C2ST

optimization:
  _file: configs/optimization/adamw.yaml

callbacks:
  _file: configs/callbacks/default_callbacks.yaml
  scatter:
    target: callbacks.BenchmarkScatterPlot
    params:
      save_every: 10