name: LOTKA_VOLTERRA_10e3_FM_baseBenchmarkFMPE

dim_flow: 4
dim_conditioning: 20
batch_size: 512

hidden_dim: 128
num_blocks: 10

_file: configs/benchmarks/benchmark_fm_baseBenchmarkFMPE.yaml

data:
  target: data.benchmarks.LotkaVolterra
  _file: configs/datasets/benchmarks/10e3_dataset.yaml



