name: LOTKA_VOLTERRA_10e4_FFJORD

dim_flow: 4
dim_conditioning: 20
batch_size: 512

_file: configs/benchmarks/benchmark_ffjord.yaml

data:
  target: data.benchmarks.LotkaVolterra
  _file: configs/datasets/benchmarks/10e4_dataset.yaml
