strategy:
  target: strategy.FlowMatching
  params:
    dim_flow: ${dim_flow}
    dim_conditioning: ${dim_conditioning}
    model:
      target: flows.models.fmpe.BaseBenchmarkFMPE
      params:
        hidden_dim: ${hidden_dim}
        num_blocks: ${num_blocks}
        out_dim: ${dim_flow}
    paths:
      name: optimal_transport
      params:
        sigma_min: 1e-4
    sampler:
      target: strategy.improved_inference.ODESolver
      params:
        solver_name: euler
        init_stepsize: 0.01

training:
  num_epochs: 2000
  num_steps_per_epoch: 1000
  batch_size: ${batch_size}

optimization:
  _file: configs/optimization/adamw.yaml

callbacks:
  checkpoint:
    target: callbacks.checkpoint.Checkpoint
    params:
      savedir: ${runtime.logdir}
      key: val_loss
  scatter:
    target: callbacks.two_dimensional.TwoDimensionalPlot
    params:
      save_every: 100
      num_samples: 3000