name: SLCP_10e3_FM_baseBenchmarkFMPE

dim_flow: 5
dim_conditioning: 8
batch_size: 512

hidden_dim: 128
num_blocks: 10

_file: configs/benchmarks/benchmark_fm_baseBenchmarkFMPE.yaml

data:
  target: data.benchmarks.SLCP
  _file: configs/datasets/benchmarks/10e3_dataset.yaml



