name: GAUSSIAN_LINEAR_UNIFORM_10e5_CNF_baseBenchmarkFMPE

dim_flow: 10
dim_conditioning: 10
batch_size: 512

hidden_dim: 128
num_blocks: 10

_file: configs/benchmarks/benchmark_cnf_baseBenchmarkFMPE.yaml

data:
  target: data.benchmarks.GaussianLinearUniform
  _file: configs/datasets/benchmarks/10e5_dataset.yaml


