name: GAUSSIAN_LINEAR_UNIFORM_10e3_NSFCL

dim_flow: 10
dim_conditioning: 10
batch_size: 512

hidden_dim: 96
steps: 6

_file: configs/benchmarks/benchmark_nsfcl.yaml

data:
  target: data.benchmarks.GaussianLinearUniform
  _file: configs/datasets/benchmarks/10e3_dataset.yaml
