name: GAUSSIAN_LINEAR_UNIFORM_10e5_FFJORD

dim_flow: 10
dim_conditioning: 10
batch_size: 512

_file: configs/benchmarks/benchmark_ffjord.yaml

data:
  target: data.benchmarks.GaussianLinearUniform
  _file: configs/datasets/benchmarks/10e5_dataset.yaml
