name: BERNOULLI_GLM_10e4_FFJORD

dim_flow: 10
dim_conditioning: 10

batch_size: 512

_file: configs/benchmarks/benchmark_ffjord.yaml

data:
  target: data.benchmarks.BernoulliGLM
  _file: configs/datasets/benchmarks/10e4_dataset.yaml

