name: BERNOULLI_GLM_10e4_NSFCL

dim_flow: 10
dim_conditioning: 10

batch_size: 512

hidden_dim: 96
steps: 6

_file: configs/benchmarks/benchmark_nsfcl.yaml

data:
  target: data.benchmarks.BernoulliGLM
  _file: configs/datasets/benchmarks/10e4_dataset.yaml

