datasetcheck:
  target: callbacks.datasetcheck.DatasetCheck
  params:
#flowcheck:
#  target: callbacks.flowcheck.FlowCheck
#  params:
#    interrupt: False
checkpoint:
  target: callbacks.checkpoint.Checkpoint
  params:
    savedir: ${runtime.logdir}
    key: val_loss