train:
  target: sbisim.data.density_estimation.ToyDataset
  params:
    data: checkerboard
    num_steps: ${num_steps}
    batch_size: ${batch_size}
val:
  target: sbisim.data.density_estimation.ToyDataset
  params:
    data: checkerboard
    num_steps: ${num_steps}
    batch_size: ${batch_size}