train:
  target: sbisim.data.GoldenRatioDataset
  params:
    n: ${num_modes}
    std_factor: ${std_factor}
    num_steps: ${num_steps_train}
    batch_size: ${batch_size}
val:
  target: sbisim.data.GoldenRatioDataset
  params:
    n: ${num_modes}
    std_factor: ${std_factor}
    num_steps: ${num_steps_val}
    batch_size: ${batch_size}