name: LOTKA_VOLTERRA_10e5_DIFF_SIMULATOR_1

dim_flow: 4
dim_conditioning: 20
dim_network: 25
context_dim: 41
start_time: 0.8

batch_size: 256

weighting: 'one'
loss_type: 'fm_ot'
scaling_type: 'none'

learning_rate: 0.001

hidden_dims: [32, 64, 128, 256, 512, 512, 512, 512, 512, 256, 128, 64, 32]

data:
  target: data.benchmarks.LotkaVolterra
  _file: configs/datasets/benchmarks/10e5_dataset.yaml

strategy:
  target: strategy.SimulatorFeedback
  params:
    dim_flow: ${dim_flow}
    dim_conditioning: ${dim_conditioning}
    weighting: ${weighting}
    loss_type: ${loss_type}
    scaling_type: ${scaling_type}
    start_time: ${start_time}
    time_alpha: 0.0
    prior:
      target: strategy.distributions.get_normal_gaussian_prior
      params:
        shape: [ 4 ]
    sampler:
      target: strategy.improved_inference.PriorODESolver
      params:
        prior:
          target: strategy.distributions.get_normal_gaussian_prior
          params:
            shape: [ 4 ]
        solver_name: euler
        init_stepsize: 0.01
    schedule:
      target: strategy.get_paths
      params:
        paths:
          name: optimal_transport
          params:
            sigma_min: 1e-4
    model_pretrained:
      target: flows.models.fmpe.SBIResidualNet
      params:
        hidden_dims: ${hidden_dims}
        out_dim: ${dim_flow}
        in_dim: ${dim_network}
        activation_fn: gelu
    weight_file_pretrained: '/home/holzschuh/projects/github/diffusion-posterior-sampling/source/simulation-based-inference/logs/LOTKA_VOLTERRA_10e5_DAX_1'
    model:
      target: flows.correction.corrector.CorrectorDifferentiableSimulator
      params:
        simulator:
          target: simulations.LotkaVolterraSimulator
        start_time: ${start_time}
        controlled_flow:
          target: flows.models.fmpe.DenseResidualNet
          params:
            hidden_dims: [ 32, 64, 128, 256, 256, 256, 128, 64, 32 ]
            out_dim: ${dim_flow}
            in_dim: 13
            activation_fn: gelu
            context_dim: 0
        aggregation:
          target: flows.models.fmpe.DenseResidualNet
          params:
            hidden_dims: [ 32, 64, 128, 256, 256, 256, 128, 64, 32 ]
            out_dim: 12
            in_dim: 40
            activation_fn: gelu
        freeze: True

training:
  num_epochs: 200
  num_steps_per_epoch: 2000
  batch_size: ${batch_size}
  early_stopping:
    patience: 7

test:
  active: True
  tests:
    c2st:
      target: callbacks.C2ST

optimization:
  _file: configs/optimization/adam.yaml

callbacks:
  checkpoint:
    target: callbacks.checkpoint.Checkpoint
    params:
      savedir: ${runtime.logdir}
      key: val_loss