name: realNVP_COND

training:

  num_epochs: 100
  num_steps_per_epoch: 1000
  batch_size: &batch_size 256

optimization:

  _file: configs/optimization/default_optimization.yaml

data:

  num_features: &num_features 2
  batch_size: *batch_size
  _file: configs/datasets/simple_moons_class.yaml

model:

  target: flows.realnvp2d.RealNVP2D
  params:
    steps: 6
    dim_flow: *num_features
    dim_conditioning: 1
    import_samples: 8

callbacks:
  _file: configs/callbacks/default_callbacks.yaml
  plots:
    target: callbacks.moons_simple.SimpleMoonDatasetPlotsConditional
    params:



