name: SIR_10e3_FM_2

dim_flow: 2
dim_conditioning: 10
batch_size: 8

residual_blocks: [[32, 1], [64, 1], [128, 1], [256, 5], [128, 1], [64, 1], [32, 1]]
gelu: [True, True, True, True, True, True, True]

learning_rate: 0.001
num_steps_per_epoch: 125
num_epochs: 200

_file: configs/benchmarks/benchmark_fm_dax.yaml

data:
  target: data.benchmarks.SIR
  _file: configs/datasets/benchmarks/10e3_dataset.yaml
