train:
  target: data.moons_simple.SimpleMoonsDataLoader
  params:
    seed: 0
    num_samples: 10000
    num_steps: 1000
    batch_size: ${data.batch_size}
    shuffle: True
    conditioning: True

val:
  target: data.moons_simple.SimpleMoonsDataLoader
  params:
    seed: 1
    num_samples: 2000
    num_steps: 100
    batch_size: ${data.batch_size}
    shuffle: False
    conditioning: True